{% set name = "kfp-notebook" %}
{% set version = "0.11.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/49/72/675e1176800c346939e396f80452ea8748cb0b0c61cdac4552ae0a0126c4/kfp_notebook-{{ version }}-py3-none-any.whl
  sha256: 02d207837a26530345e78b54c910c8d51a92fa005cf9910761e14a9672f0677c

build:
  number: 0
  skip: True  # [not unix]
  script: "{{ PYTHON }} -m pip install kfp_notebook-{{ version }}-py3-none-any.whl --no-deps -vv"

requirements:
  build:
  host:
    - python >=3.6
    - setuptools
    - pip
  run:
    - python >=3.6
    - click >=6.0
    - bumpversion >=0.5.3
    - wheel >=0.30.0
    - watchdog >=0.8.3
    - flake8 >=3.5.0
    - tox >=2.9.1
    - coverage >=4.5.1
    - twine >=1.10.0
    - kfp >=0.5.1

test:
  imports:
    - kfp_notebook

about:
  home: https://github.com/elyra-ai/kfp-notebook
  dev_url: https://github.com/elyra-ai/kfp-notebook
  doc_url: https://github.com/elyra-ai/kfp-notebook/blob/master/README.md
  doc_source_url: https://github.com/elyra-ai/kfp-notebook/tree/master/docs
  license: Apache-2.0
  license_file: LICENSE
  summary: "KFP-Notebook is an operator that enable running notebooks as part of a Kubeflow Pipeline"
  description: >
    KFP-Notebook is an operator that enable running notebooks as part of a Kubeflow Pipeline

extra:
  recipe-maintainers:
    - akchinSTC
    - lresende
