{% set name = "elyra-r-editor-extension" %}
{% set version = "2.2.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/elyra-r-editor-extension-{{ version }}.tar.gz
  sha256: 8d6d403dcf964cb0b388c5a5f6ffb9fec08925c538a0d9f01b83c0601b211229

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - elyra-server ==2.2.4
    - python >=3.6

test:
  imports:
	- elyra_r_editor_extension
  commands:
	- pip check
  requires:
	- pip


about:
  home: https://github.com/elyra-ai/elyra
  summary: Elyra JupyterLab extension providing support for R scripts. Learn more at https://elyra.readthedocs.io/en/stable/user_guide/enhanced-script-support.html
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - akchinSTC
    - lresende
